disabled_rules:

opt_in_rules:
-empty_count

excluded:
- Carthage
- Pods

line_length:
  warning: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true
